config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'sessions#index'
  #sessions
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: 'sessions#create'
  post '/signout', to: 'sessions#destroy', as: 'signout'
  get '/signout', to: 'sessions#destroy'

  #users
  get '/users/new', to: 'users#new', as: 'signup'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#delete'

  #groups
  get '/groups', to: 'groups#index'
  get '/groups/new', to: 'groups#new', as: 'new_group'
  post '/groups', to: 'groups#create'
  get '/groups/:id', to: 'groups#show', as: 'group'
  get '/groups/:id/edit', to: 'groups#edit', as: 'edit_group'
  patch '/groups/:id', to: 'groups#update'
  delete '/groups/:id', to: 'groups#delete'


  #attendances
  post '/groups/:id/attendances', to: 'attendances#create', as: 'attendances'
  delete '/groups/:id/attendances', to: 'attendances#delete'
  # delete 'groups/:id/attendances', to 'attendances#delete'

  #Notes
  post '/notes', to: 'notes#create'

  #see nested routes



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :notes
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  has_many :notes, through: :attendances
  belongs_to :admin, :class_name => 'User'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :attendance
  delegate :user, :to => :attendance
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :attendances
  has_many :groups, through: :attendances
  has_many :notes, through: :attendances
  has_many :created_groups, :class_name => "Group", :foreign_key => 'admin_id'

  validates :name, presence: true, uniqueness: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :happened?, :admin?

  def happened?(event)
    event.time < Time.now
  end

  def admin?(user, g)
    !!(user.id == g.admin_id)
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def new

  end

  def create
    if set_user
      if find_group_with_params
        @attendance = Attendance.new(user_id: @user.id, group_id: @group.id)
        if @attendance.save
          redirect_to group_path(@group)
        else
          flash[:message] = "There was a problem joining your group, please try again"
          render group_path(@group)
        end
      else
        flash[:message] = "There was a problem finding your group, please try again"
        redirect_to user_path(@user)
      end
    else
      flash[:message] = "This is only available to users who have logged in. Please login and try again"
      render signin_path
    end
  end

  def delete
    set_user
    find_group_with_params
    @attendance = Attendance.find_by(user_id: @user.id, group_id: @group.id)
    @attendance.destroy
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find_by(id: session[:user_id])
  end

  def find_group_with_params
    @group = Group.find(params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    set_user
    @groups = Group.order(time: :DESC)
  end

  def new
    @group = Group.new
    set_user
  end

  def create
    set_user
    @group = Group.new(params.require(:group).permit(:topic, :location, :time, :admin_id))
    if @group.save
      Attendance.create(user_id: @user.id, group_id: @group.id)
      flash[:message] = "Study Group: #{@group.topic} successfully created!"
      redirect_to group_path(@group)
    else
      flash[:message] = "Please fill out all the fields."
      render :new
    end
  end

  def edit
    if set_user
      find_group_with_params
      if @user.id == @group.admin_id
      else
        flash[:message] = "You need to be the creator of a Study Group to edit the event."
        redirect_to user_path(@user)
      end
    else
      flash[:message] = "You need to be signed in to edit an event."
      redirect_to signin_path
    end
  end

  def update
    set_user
    find_group_with_params
    if @user.id == params[:group][:admin_id].to_i
      @group.update(params.require(:group).permit(:topic, :location, :time, :admin_id))
      redirect_to group_path(@group)
    else
      flash[:message] = "You need to be the creator of a Study Group to edit the event."
      redirect_to user_path(@user)
    end
  end

  def delete
    set_user
    find_group_with_params
    if @user.id == @group.admin_id
      flash[:message] = "Study Group: #{@group.topic} successfully deleted"
      @group.destroy
      redirect_to user_path(@user)
    else
      flash[:message] = "You need to be the creator of a Study Group to edit the event."
      redirect_to user_path(@user)
    end
  end

  def show
    if set_user
      @note = Note.new
      find_group_with_params
      @attendance = Attendance.new
    else
      flash[:message] = "Please sign in to see Study Group details"
      redirect_to signin_path
    end
  end

  private

  def set_user
    @user = User.find_by(id: session[:user_id])
  end

  def find_group_with_params
    @group = Group.find(params[:id])
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @user = User.find_by(id: session[:user_id])
    @group = Group.find_by(id: params[:note][:group_id])
    @note = Note.new(content: params[:note][:content], attendance:Attendance.find_or_create_by(user: @user, group: @group))
    @note.save
    redirect_to group_path(@group)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    if session[:user_id]
      @user = User.find(session[:user_id])
      redirect_to user_path(@user)
    end
  end

  def new
  end

  def create
    @user = User.find_by(name: params[:user][:name].downcase)
    if @user.present? && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:message] = "incorrect username/password"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        redirect_to signup_path
      end
    else
      flash[:message] = "Sorry the username " + @user.name + ' is already taken. Please choose another.'
       @user.errors.full_messages.join(". ")
      render signup_path
    end
  end

  def edit
    set_user
  end

  def update
    set_user
    if @user.id == session[:user_id]
      @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:message] = "Please signin to view this page"
      redirect_to signin_path
    end
  end

  def delete
    set_user
    if @user.id == session[:user_id]
      Attendance.all.each do |attendance|
        if attendance.admin_id == @user.id
          attendance.destroy
        end
      end
      flash[:message] = "User: #{@user.name} has been successfully deleted."
      redirect_to signup_path
    else
      flash[:message] = "You can only delete your user account"
      redirect_to signin_path
    end
  end

  def show
    if set_user
      if @user.id == session[:user_id]
        @groups = (Group.where(admin_id: @user.id).order('time') + @user.groups).uniq
      else
        flash[:message] = "Please signin to view this page"
        redirect_to signin_path
      end
    else
      redirect_to signin_path
    end
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params[:user][:name] = params[:user][:name].downcase
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.erb
<h1>Edit Group Page</h1>

<% if flash[:message] %>
<div>
  <%= flash[:message] %>
</div>
<% end %>

<%= form_for @group, method: 'patch' do |f| %>
<%= f.label :topic %>
<%= f.text_field :topic %>
<%= f.label :location %>
<%= f.text_field :location %>
<%= f.label :time %>
<%= f.datetime_field :time %>
<%= f.hidden_field :admin_id, value: @user.id %>
<%= f.submit "Edit Group", class: "waves-effect waves-light btn" %>
<% end %>

<br>

<%= form_for @group, method: 'delete' do |f| %>
  <%= f.submit "Delete Study Group", class: "waves-effect waves-light btn"%>
<% end %>

app/views/groups/index.html.erb
<h1>Study Groups</h1>


<table class="bordered highlight">
  <thead>
    <tr>
        <th>Topic</th>
        <th>Date</th>
        <th>Time</th>
        <th>Location</th>
        <th>Status</th>
        <th>More Details</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |g| %>
    <tr>
      <td><%= g.topic %></td>
      <td><%= g.time.strftime("%a, %B %d, %Y") %></td>
      <td><%= g.time.strftime("%I:%M %p") %></td>
      <td><%= g.location %></td>
      <td><% if happened?(g) %>
        <%= "This Study Group alreay met" %>
      <% else %>
        <% if g.users.include?(@user) %>
          <% if admin?(@user, g) %>
          <%= "You're Running the Show" %>
          <% else %>
          <%= "You're signed up" %>
          <% end %>
        <% else %>
        <%= "Join!" %>
        <% end %>
      <% end %></td>
      <td><%= link_to "details page", group_path(g) %></td>

    </tr>
    <% end %>
  </tbody>

</table>

app/views/groups/new.html.erb
<% if flash[:message] %>
<div>
  <%= flash[:message] %>
</div><br>
<% end %>

<h1>Create a Study Group</h1>

<%= form_for(@group) do |f| %>
<%= f.label :topic %>
<%= f.text_field :topic %>
<%= f.label :location %>
<%= f.text_field :location %>
<%= f.label :time %>
<%= f.datetime_field :time %>
<%= f.hidden_field :admin_id, value: @user.id %>
<a class="waves-effect waves-light btn"><%= f.submit "Create Study Group" %></a>
<% end %>

app/views/groups/show.html.erb
<h1>Study Group</h1>

<% if flash[:message] %>
<div>
  <%= flash[:message] %>
</div>
<% end %>

<div class="row">
  <div class="col s6">
    <div class="card teal darken-1">
      <div class="card-content white-text">
        <span class="card-title">Topic: <%= @group.topic %></span>

          <ul>
            <span style="font-weight: bold">Location: </span><%= @group.location %>
          </ul>
          <ul>
            <span style="font-weight: bold">Date: </span><%= @group.time.strftime("%a, %B %d, %Y") %>
          </ul>
          <ul>
            <span style="font-weight: bold">Time: </span><%= @group.time.strftime("%I:%M %p") %>
          </ul>
          <ul>
            <span style="font-weight: bold">Attending: </span>
            <% list = @group.users.map { |user| user.name.capitalize } %>
            <%= list.split(" ").join(", ") %>
          </ul>
          <ul>
            <span style="font-weight: bold">Admin: </span> <%= @group.admin.name.capitalize %>
          </ul>
          </div>
      <div class="card-action">
        <% if happened?(@group) %>
        <div class="card-content white-text">
          <%= "This Study Group already met." %>
        </div>
        <% else %>
        <% if @group.users.include?(@user) %>
        <% if admin?(@user, @group) %>
        <div class="row">
          <div class="col">
            <%= link_to "Edit Group", edit_group_path(@group), class: "waves-effect waves-light btn" %>
          </div>
          <div class="col">
            <%= form_for @group, method: 'delete' do |f| %>
              <%= f.button "Delete Group", class: "waves-effect waves-light btn" %>
            <% end %>
          </div>
        </div>
            <% else %>
              <%= form_for @attendance, method: 'delete' do |f| %>
                <%= f.button "Leave Group", class: "waves-effect waves-light btn" %>
              <% end %>
            <% end %>
          <% else %>
            <%= form_for(@attendance) do |f| %>
              <%= f.button "Join Group", class: "waves-effect waves-light btn" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
  <h5>Comments:</h5>
  <ul>
  <% if @group.notes.any? %>
    <% @group.notes.each do |note| %>
    <li>
      <ul>
        From <%= note.user.name.capitalize %> at <%= note.created_at.strftime("%I:%M %p") %> on <%= note.created_at.strftime("%a, %B %d, %Y") %>.
      </ul>
      <ul>
        Comment: <%= note.content %>
      </ul><br>
    </li>
    <% end %>
    <% else %>
      <%= "There are no comments yet. Start the discussion!" %>
    <% end %>
  </ul>

<h5>Join the discussion:</h5>
<%= form_for(@note) do |f| %>
<%= f.label :content, "Your Comment:" %>
<%= f.text_area :content, class:"materialize-textarea" %>
<%= f.hidden_field :group_id, value: @group.id %>
<%= f.submit "Submit your comment", class: "waves-effect waves-light btn" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProjectStudyGroups</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <div class="nav-wrapper teal">
      <a href="/" class="brand-logo">My Study Groups</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/groups">View Study Groups</a></li>

        <% if session[:user_id] %>
        <li><%= link_to "Create Study Group", new_group_path %></li>
        <li><%= link_to "Edit Profile", edit_user_path(@user) %></li>
        <li><%= link_to "Sign Out", signout_path %></li>
        <% else %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/new.html.erb
<h1>New Note</h1>
<h3>For Study Group: <%= @group.topic %>: </h3>

<%= form_for @note do %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Profile:</h1>

  <% if flash[:message] %>
  <%= flash[:message] %>
  <% end %>

<%= form_for(@user, method: 'patch') do |f| %>
<div >
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div >
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<div >
  <%= f.submit "Submit", class: "waves-effect waves-light btn" %>
</div>
<% end %><br>

<%= form_tag ({controller: 'users', action: 'delete', method: 'post'}) do %>
  <input type=submit value="Delete My Profile", class="waves-effect waves-light btn">
<% end %>

app/views/users/new.html.erb
<div>
  <% if flash[:message] %>
  <%= flash[:message] %>
  <% end %>
</div><br>

<h1>New User Signup:</h1>

<%= form_for(@user) do |f| %>
<div >
  <%= f.label :name %>
  <%= f.text_field :name %>
</div><br>
<div >
  <%= f.label :password %>
  <%= f.password_field :password %>
</div><br>
<div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div><br>
<div >
  <%= f.submit "Create User", class:"waves-effect waves-light btn" %>
</div><br>
<% end %>

app/views/users/show.html.erb
<% if flash[:message] %>
<div>
  <%= flash[:message] %>
</div><br>
<% end %>

<h1>Hi <%= @user.name.capitalize %></h1>
<div class="row">
  <div class="col s6">
    <div class="card teal darken-1">
      <div class="card-content white-text">
        <span class="card-title">Upcoming Study Groups</span>
          <% if @groups.length > 0 %>
            <% @groups.each do |g| %>
              <% if !happened?(g)%>
                <li>
                  <%= g.topic %> is happening on <%= g.time.strftime("%a, %B %d, %Y") %> at <%= g.time.strftime("%I:%M %p") %> in <%= g.location %>.<br>
                  <%= link_to "More Details", group_path(g), {:style=>'color:#ff8a80;', :class => "css_class"}  %>
                </li>
              <% end %>
            <% end %>
          <% else %>
            <%= "You haven't signed up for any Study Groups!" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col s6">
      <div class="card teal darken-1">
        <div class="card-content white-text">
          <span class="card-title">Past Study Groups</span>
          <% if @groups.length > 0 %>
            <% @groups.each do |g| %>
              <% if happened?(g) %>
              <li>
                <%= g.topic %> is happening on <%= g.time.strftime("%a, %B %d, %Y") %> at <%= g.time.strftime("%I:%M %p") %> in <%= g.location %>.<br>
                <%= link_to "More Details", group_path(g), {:style=>'color:#ff8a80;', :class => "css_class"} %>
              </li>
              <% end %>
            <% end %>
          <% else %>
            <%= "You haven't attended any Study Groups!" %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>